replicaCount: 1 # HPA handles replicas for high-availability

image:
  repository: zayedmahmud/password-generator
  pullPolicy: IfNotPresent

  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

strategy:
  maxSurge: 30%
  maxUnavailable: 25%
minReadySeconds: 5

podLabels:
  app: zhm
  environment: demo

podSecurityContext:
  fsGroup: 999 ## uid/gid of 'appuser'
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: false ## if nothing is written to disk, set to 'true'
  runAsUser: 999 ## uid/gid of 'appuser'

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  hosts:
    - host:
      paths:
        - path: /
          pathType: ImplementationSpecific
